# SPDX-FileCopyrightText: Copyright (c) 2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
merge:
  script: |-
    echo 'nothing to do'
